# Importación de librerías

In [15]:
from tqdm import tqdm
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import filters_and_features as ff
import data_processor as dp
import numpy as np

# Importación de datos

In [2]:
df = dp.lectura()

Se crea el dataframe df_block

In [3]:
df_block = dp.create_df_block(df)
# del df

Se limpia y visualiza el contenido

In [6]:
dp.balance(df_block)
df_block['stimulus'].value_counts()

stimulus
1     132
0     132
3     132
4     132
6     132
9     132
10    132
11    132
Name: count, dtype: int64

# Filtro

In [7]:
df_block_filtered = dp.filtrar(df_block)
# del df_block

Procesando: 100%|██████████| 3/3 [00:26<00:00,  8.79s/it]

# Extracción de características

In [8]:
df_block_features = dp.gen_carac(df_block_filtered)
# del df_block_filtered

Extrayendo Características: 100%|██████████| 1056/1056 [00:31<00:00, 33.08it/s]

In [9]:
df_block_features.describe()

,rms_1,iemg_1,mav_1,wl_1,log_detec_1,ssi_1,fft_1,psd_1,mf_1,mdf_1,...,mav_14,wl_14,log_detec_14,ssi_14,fft_14,psd_14,mf_14,mdf_14,zc_14,stimulus
count,1056.000000,1.056000e+03,1056.000000,1056.000000,1056.000000,1.056000e+03,1056.000000,1.056000e+03,1056.000000,1056.000000,...,1056.000000,1056.000000,1.056000e+03,1.056000e+03,1056.000000,1.056000e+03,1056.000000,1056.000000,1056.000000,1056.000000
mean,0.000034,4.693922e-08,0.000020,0.112569,0.000009,6.995103e-09,0.001946,1.507262e-12,217.449276,81.914773,...,0.000005,0.020962,2.906786e-06,1.213184e-09,0.000372,2.970708e-13,180.623041,46.659091,1429.200758,5.500000
std,0.000017,2.351786e-07,0.000009,0.061759,0.000003,8.120465e-09,0.001048,1.696341e-12,22.756036,16.792583,...,0.000004,0.009324,1.363055e-06,2.660676e-08,0.000426,6.857602e-12,15.066878,9.415590,182.233576,3.906975
min,0.000008,-1.174226e-06,0.000005,0.016605,0.000002,2.312092e-10,0.000373,6.547629e-14,176.314297,48.000000,...,0.000002,0.005752,9.797974e-07,1.384843e-11,0.000092,3.691819e-15,97.554654,12.000000,681.000000,0.000000
25%,0.000023,-5.616204e-08,0.000014,0.068804,0.000007,2.397544e-09,0.001249,5.450836e-13,200.793461,69.750000,...,0.000003,0.014507,2.086666e-06,9.939096e-11,0.000241,2.124460e-14,172.664882,41.000000,1339.000000,2.500000
50%,0.000030,4.959215e-08,0.000019,0.097248,0.000009,4.239948e-09,0.001667,9.360721e-13,211.187295,78.000000,...,0.000004,0.019278,2.554305e-06,1.836005e-10,0.000321,3.926108e-14,182.149929,46.000000,1454.500000,5.000000
75%,0.000040,1.565826e-07,0.000024,0.138057,0.000011,7.746937e-09,0.002256,1.633116e-12,231.110911,94.000000,...,0.000006,0.025992,3.603728e-06,3.683774e-10,0.000448,8.007232e-14,190.123314,53.000000,1549.250000,9.250000
max,0.000105,1.333975e-06,0.000056,0.380752,0.000022,5.462246e-08,0.006225,1.123311e-11,282.585742,123.000000,...,0.000098,0.150995,1.735379e-05,8.629341e-07,0.012427,2.225473e-10,227.873480,77.000000,1855.000000,11.000000

# Normalización

In [10]:
df_block_normalized = dp.normalizar(df_block_features)
# del df_block_features

In [11]:
df_block_normalized.describe()

,rms_1,iemg_1,mav_1,wl_1,log_detec_1,ssi_1,fft_1,psd_1,mf_1,mdf_1,...,mav_14,wl_14,log_detec_14,ssi_14,fft_14,psd_14,mf_14,mdf_14,zc_14,stimulus
count,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1056.000000,1.056000e+03,1.056000e+03,1.056000e+03,...,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1.056000e+03,1056.000000
mean,-1.884015e-16,-3.364312e-17,-4.037175e-17,-1.076580e-16,1.749442e-16,8.074349e-17,0.000000,5.382900e-17,7.536059e-16,-3.498885e-16,...,-1.345725e-16,-8.074349e-17,-5.382900e-17,1.009294e-17,1.076580e-16,3.364312e-18,5.113755e-16,2.153160e-16,3.768030e-16,5.500000
std,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474,1.000474e+00,1.000474e+00,1.000474e+00,...,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,1.000474e+00,3.906975
min,-1.559187e+00,-5.194963e+00,-1.795006e+00,-1.554580e+00,-2.002664e+00,-8.333388e-01,-1.501971,-8.503414e-01,-1.808508e+00,-2.020585e+00,...,-9.015479e-01,-1.632132e+00,-1.414398e+00,-4.509772e-02,-6.579295e-01,-4.280184e-02,-5.515924e+00,-3.682776e+00,-4.107669e+00,0.000000
25%,-6.738130e-01,-4.386034e-01,-7.316287e-01,-7.089762e-01,-7.303064e-01,-5.664377e-01,-0.665764,-5.674769e-01,-7.322763e-01,-7.247567e-01,...,-4.189812e-01,-6.927276e-01,-6.019633e-01,-4.188113e-02,-3.066567e-01,-4.024102e-02,-5.284393e-01,-6.013189e-01,-4.952078e-01,2.500000
50%,-2.535017e-01,1.128583e-02,-1.747049e-01,-2.481875e-01,-1.011553e-01,-3.394461e-01,-0.267043,-3.368783e-01,-2.753093e-01,-2.332356e-01,...,-1.947588e-01,-1.807691e-01,-2.587187e-01,-3.871466e-02,-1.181388e-01,-3.761255e-02,1.013887e-01,-7.003312e-02,1.388944e-01,5.000000
75%,3.299549e-01,4.664342e-01,4.941671e-01,4.128984e-01,5.875260e-01,9.262900e-02,0.295782,7.422699e-02,6.006366e-01,7.200175e-01,...,3.089654e-01,5.396992e-01,5.115506e-01,-3.176663e-02,1.802331e-01,-3.165849e-02,6.308390e-01,6.737670e-01,6.590779e-01,9.250000
max,4.196066e+00,5.475183e+00,4.209458e+00,4.344478e+00,4.010680e+00,5.867881e+00,4.085211,5.736146e+00,2.863738e+00,2.447789e+00,...,2.367440e+01,1.395331e+01,1.060401e+01,3.240263e+01,2.833152e+01,3.242468e+01,3.137533e+00,3.223939e+00,2.337665e+00,11.000000

# Creación de dataframes de entrenamiento y testeo

In [12]:
y_block = df_block_normalized.iloc[:, -1]
X_block = df_block_normalized.iloc[:, :-1]
X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(X_block, y_block,
                                                    random_state=100,
                                                    test_size=0.30,
                                                    shuffle=True)

# del df_block_normalized

In [13]:
print(X_train_b.shape,y_train_b.shape)

(739, 154) (739,)

# Entrenamiento y testeo del modelo

Importamos librerías

In [37]:
# Random forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Rotation forest
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from scipy.stats import mode

# Artificial Neural Networks (ANN)
import setuptools.dist
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

# Hidden Markov model (HMM)
from hmmlearn import hmm
from sklearn.preprocessing import LabelEncoder

Random forest

In [38]:
rf_b = RandomForestClassifier(
    max_depth=20,             # Profundidad máxima de los árboles
    criterion='entropy',      # Criterio de medida para la calidad de la división ('entropy' o 'gini')
    min_samples_split=4,      # Número mínimo de muestras requeridas para dividir un nodo
    random_state=99,          # Para reproducibilidad del modelo
    n_estimators=3000,        # Número de árboles en el bosque
    verbose=1,                # Imprimir información durante el entrenamiento
    oob_score=True,           # Calcular la precisión del modelo fuera de la bolsa (OOB)
    n_jobs=-1                 # Usar todos los procesadores disponibles para acelerar el entrenamiento
)
rf_b.fit(X_train_b, y_train_b)
y_pred_b_RanF = rf_b.predict(X_test_b)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 168 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 418 tasks      | elapsed:    0.5s
[Parallel(n_jobs=-1)]: Done 768 tasks      | elapsed:    1.0s
[Parallel(n_jobs=-1)]: Done 1218 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-1)]: Done 1768 tasks      | elapsed:    2.3s
[Parallel(n_jobs=-1)]: Done 2418 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:    3.9s finished
[Parallel(n_jobs=16)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done 168 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done 418 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done 768 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done 1218 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done 1768 tasks      | elapsed:    0.1s
[Parallel(n_jobs=16)]: Done 2418 tasks      | elapsed:    0.2s
[Parallel(n_jobs=16)]: Done 3000 out of 3000 | elapsed:    0.3s finished

Rotation forest

In [58]:
class RotationForest:
    def __init__(self, n_estimators=10, n_subsets=3):
        self.n_estimators = n_estimators
        self.n_subsets = n_subsets
        self.models = []

    def fit(self, X, y):
        for _ in range(self.n_estimators):
            # Crear submodelos
            model = RandomForestClassifier()  # Clasificador base
            
            # Dividir las características en subconjuntos y rotar cada uno
            n_features = X.shape[1]
            subsets = np.array_split(np.arange(n_features), self.n_subsets)
            X_rotated = np.zeros_like(X)
            for subset in subsets:
                # Rotar el subconjunto con PCA
                pca = PCA()
                X_rotated[:, subset] = pca.fit_transform(X[:, subset])
            
            # Entrenar modelo en el conjunto rotado
            cloned_model = clone(model)
            cloned_model.fit(X_rotated, y)
            self.models.append(cloned_model)

    def predict(self, X):
        # Realizar predicciones y tomar el voto mayoritario
        predictions = np.zeros((X.shape[0], len(self.models)))
        for idx, model in enumerate(self.models):
            predictions[:, idx] = model.predict(X)
        return np.apply_along_axis(lambda x: np.bincount(x.astype(int)).argmax(), axis=1, arr=predictions)

# Entrenamiento del modelo Rotation Forest
rot_forest = RotationForest(n_estimators=10, n_subsets=3)

rot_forest.fit(X_train_b, y_train_b)

# Predicción
#y_pred_b_RotF = rot_forest.predict(X_test_b)

InvalidIndexError: (slice(None, None, None), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51]))

Artificial Neural Networks (ANN)

In [51]:
le = LabelEncoder()
y_train_b_enc = le.fit_transform(y_train_b)  # Transforma las etiquetas a valores consecutivos (0 a 7)
y_test_b_enc = le.transform(y_test_b)

# Asegurarse de que el número de clases sea correcto
num_classes = len(np.unique(y_train_b_enc))
print("Número de clases detectadas en y_train_b:", num_classes)  # Esto debería ser 8

# Convertir a formato categórico
y_train_b_cat = to_categorical(y_train_b_enc, num_classes=num_classes)
y_test_b_cat = to_categorical(y_test_b_enc, num_classes=num_classes)

# Definir y entrenar la red neuronal
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_b.shape[1],)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')  # La capa de salida ahora usa 8 neuronas, una por clase
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train_b, y_train_b_cat, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

# Predicción y decodificación
y_pred_probs = model.predict(X_test_b)
y_pred_ann = np.argmax(y_pred_probs, axis=1)
y_pred_ann_original = le.inverse_transform(y_pred_ann)  # Convertir a las etiquetas originales

Número de clases detectadas en y_train_b: 8
Epoch 1/50

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.2274 - loss: 2.0192 - val_accuracy: 0.4730 - val_loss: 1.3841
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6069 - loss: 1.1872 - val_accuracy: 0.6486 - val_loss: 1.0395
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7323 - loss: 0.8291 - val_accuracy: 0.7297 - val_loss: 0.7741
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7663 - loss: 0.6210 - val_accuracy: 0.7838 - val_loss: 0.6337
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8668 - loss: 0.4601 - val_accuracy: 0.8041 - val_loss: 0.5242
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8314 - loss: 0.4870 - val_accuracy: 0.7973 - val_loss: 0.5103
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8667 - loss: 0.3896 - val_accuracy: 0.8176 - val_loss: 0.4909
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9086 - loss: 0.2681 - val_accuracy: 0.8784 - val_loss: 0.4009
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9158 - loss: 0.2620 - val_accuracy: 0.8514 - val_loss: 0.4287
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9167 - loss: 0.2307 - val_accuracy: 0.8716 - val_loss: 0.3993
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9364 - loss: 0.2182 - val_accuracy: 0.8446 - val_loss: 0.4293
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9371 - loss: 0.1976 - val_accuracy: 0.8649 - val_loss: 0.3870
Epoch 13/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9413 - loss: 0.1976 - val_accuracy: 0.8716 - val_loss: 0.4101
Epoch 14/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9343 - loss: 0.1785 - val_accuracy: 0.8716 - val_loss: 0.3698
Epoch 15/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9497 - loss: 0.1672 - val_accuracy: 0.8851 - val_loss: 0.3507
Epoch 16/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9546 - loss: 0.1473 - val_accuracy: 0.8919 - val_loss: 0.3755
Epoch 17/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9678 - loss: 0.1177 - val_accuracy: 0.8986 - val_loss: 0.3690
Epoch 18/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9686 - loss: 0.1077 - val_accuracy: 0.8716 - val_loss: 0.3677
Epoch 19/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9637 - loss: 0.1074 - val_accuracy: 0.8919 - val_loss: 0.3654
Epoch 20/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9794 - loss: 0.0968 - val_accuracy: 0.8919 - val_loss: 0.3772
Epoch 21/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9757 - loss: 0.0816 - val_accuracy: 0.8851 - val_loss: 0.3839
Epoch 22/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9559 - loss: 0.1209 - val_accuracy: 0.9122 - val_loss: 0.3549
Epoch 23/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9650 - loss: 0.0949 - val_accuracy: 0.9122 - val_loss: 0.3633
Epoch 24/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9812 - loss: 0.0853 - val_accuracy: 0.8986 - val_loss: 0.3903
Epoch 25/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9765 - loss: 0.0824 - val_accuracy: 0.9189 - val_loss: 0.3658
Epoch 26/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9675 - loss: 0.0877 - val_accuracy: 0.9054 - val_loss: 0.3925
Epoch 27/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9916 - loss: 0.0468 - val_accuracy: 0.9122 - val_loss: 0.3787
Epoch 28/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9693 - loss: 0.0743 - val_accuracy: 0.9189 - val_loss: 0.3657
Epoch 29/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9824 - loss: 0.0597 - val_accuracy: 0.9189 - val_loss: 0.3985
Epoch 30/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9826 - loss: 0.0551 - val_accuracy: 0.9054 - val_loss: 0.4300
Epoch 31/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9850 - loss: 0.0785 - val_accuracy: 0.9054 - val_loss: 0.4009
Epoch 32/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9724 - loss: 0.0624 - val_accuracy: 0.9189 - val_loss: 0.3719
Epoch 33/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9835 - loss: 0.0526 - val_accuracy: 0.9324 - val_loss: 0.3407
Epoch 34/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9739 - loss: 0.0657 - val_accuracy: 0.9054 - val_loss: 0.3474
Epoch 35/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9894 - loss: 0.0400 - val_accuracy: 0.8919 - val_loss: 0.4306
Epoch 36/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9856 - loss: 0.0527 - val_accuracy: 0.8784 - val_loss: 0.4671
Epoch 37/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9724 - loss: 0.0642 - val_accuracy: 0.9054 - val_loss: 0.3868
Epoch 38/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9790 - loss: 0.0639 - val_accuracy: 0.8919 - val_loss: 0.4286
Epoch 39/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0325 - val_accuracy: 0.9122 - val_loss: 0.3749
Epoch 40/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9915 - loss: 0.0412 - val_accuracy: 0.8986 - val_loss: 0.4533
Epoch 41/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9745 - loss: 0.0706 - val_accuracy: 0.9054 - val_loss: 0.3895
Epoch 42/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9775 - loss: 0.0578 - val_accuracy: 0.9054 - val_loss: 0.4028
Epoch 43/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9706 - loss: 0.1394 - val_accuracy: 0.9054 - val_loss: 0.4155
Epoch 44/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9758 - loss: 0.0736 - val_accuracy: 0.9122 - val_loss: 0.3951
Epoch 45/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9883 - loss: 0.0532 - val_accuracy: 0.9189 - val_loss: 0.3752
Epoch 46/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0306 - val_accuracy: 0.9122 - val_loss: 0.4161
Epoch 47/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9921 - loss: 0.0258 - val_accuracy: 0.8986 - val_loss: 0.4451
Epoch 48/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9863 - loss: 0.0442 - val_accuracy: 0.8986 - val_loss: 0.3824
Epoch 49/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9933 - loss: 0.0319 - val_accuracy: 0.8986 - val_loss: 0.4532
Epoch 50/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9922 - loss: 0.0331 - val_accuracy: 0.8986 - val_loss: 0.4424
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

# Resultados

Random forest

In [42]:
confusion_matrix(y_pred_b_RanF, y_test_b)

array([[42,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 36,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 29,  3,  2,  0,  0,  0],
       [ 0,  0,  4, 39,  2,  0,  1,  0],
       [ 0,  0,  8,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  1,  0, 31,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 41,  0],
       [ 0,  2,  0,  0,  0,  2,  0, 36]])

In [43]:
accuracy_score(y_pred_b_RanF, y_test_b)

0.917981072555205

In [44]:
print(classification_report(y_pred_b_RotF, y_test_b))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        41
           1       0.92      1.00      0.96        35
           3       0.68      0.88      0.77        32
           4       0.93      0.82      0.87        49
           6       0.93      0.81      0.86        47
           9       0.88      0.88      0.88        33
          10       0.95      0.98      0.96        41
          11       0.89      0.85      0.87        39

    accuracy                           0.90       317
   macro avg       0.90      0.90      0.89       317
weighted avg       0.90      0.90      0.90       317

Rotation forest

In [45]:
confusion_matrix(y_pred_b_RotF, y_test_b)

array([[41,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 35,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 28,  2,  1,  0,  0,  0],
       [ 0,  0,  4, 40,  2,  0,  2,  1],
       [ 0,  0,  9,  0, 38,  0,  0,  0],
       [ 1,  0,  0,  0,  0, 29,  0,  3],
       [ 0,  0,  0,  0,  0,  1, 40,  0],
       [ 0,  2,  0,  1,  0,  3,  0, 33]])

In [46]:
accuracy_score(y_pred_b_RotF, y_test_b)

0.8958990536277602

In [47]:
print(classification_report(y_pred_b_RotF, y_test_b))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        41
           1       0.92      1.00      0.96        35
           3       0.68      0.88      0.77        32
           4       0.93      0.82      0.87        49
           6       0.93      0.81      0.86        47
           9       0.88      0.88      0.88        33
          10       0.95      0.98      0.96        41
          11       0.89      0.85      0.87        39

    accuracy                           0.90       317
   macro avg       0.90      0.90      0.89       317
weighted avg       0.90      0.90      0.90       317

Artificial Neural Networks (ANN)

In [53]:
confusion_matrix(y_pred_b_ann, y_test_b)

array([[42,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 36,  1,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 41,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  1,  0, 38,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 32,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 42,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  1,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [49]:
accuracy_score(y_pred_b_ann, y_test_b)

0.2555205047318612

In [50]:
print(classification_report(y_pred_b_ann, y_test_b))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       0.97      1.00      0.99        37
           2       0.00      0.00      0.00        39
           3       0.02      0.02      0.02        43
           4       0.02      0.02      0.02        43
           5       0.00      0.00      0.00        32
           6       0.00      0.00      0.00        42
           7       0.00      0.00      0.00        39
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         0

    accuracy                           0.26       317
   macro avg       0.18      0.19      0.18       317
weighted avg       0.25      0.26      0.25       317

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Hidden Markov model (HMM)